import type { KnowledgeBaseItem, KnowledgeTag } from "./types";

export const knowledgeTypeLabels = {
  metric_definition: "指标定义",
  dimension_definition: "维度定义",
  entity_definition: "业务实体",
  field_mapping: "字段映射",
  formula_definition: "口径公式",
  business_rule: "业务规则",
  lineage_note: "数据链路",
  report_logic: "报表逻辑",
  verified_conclusion: "探索结论",
} as const;

export const knowledgeStatusLabels = {
  draft: "草稿",
  pending: "待认证",
  approved: "已认证",
  conflicted: "有冲突",
  expired: "已过期",
} as const;

export const knowledgeSourceLabels = {
  manual: "手动创建",
  exploration: "探索沉淀",
  import: "导入",
} as const;

export const knowledgeVisibilityLabels = {
  personal: "个人",
  team: "团队",
  company: "全公司",
} as const;

export const semanticTypes = [
  "metric_definition",
  "dimension_definition",
  "entity_definition",
  "field_mapping",
  "formula_definition",
] as const;

export const demoKnowledgeTags: KnowledgeTag[] = [
  { name: "财务指标", group: "业务域", count: 4 },
  { name: "运营指标", group: "业务域", count: 3 },
  { name: "销售分析", group: "场景", count: 5 },
  { name: "用户标签", group: "对象", count: 2 },
  { name: "库存分析", group: "场景", count: 2 },
  { name: "报表口径", group: "来源", count: 5 },
  { name: "数据链路", group: "技术", count: 3 },
  { name: "Agent 可用", group: "治理", count: 6 },
];

export const demoKnowledgeItems: KnowledgeBaseItem[] = [
  {
    id: "kn_metric_gross_profit",
    title: "毛利率",
    type: "metric_definition",
    status: "approved",
    source: "manual",
    content: "销售毛利占销售收入的比例，用于判断商品、渠道和店铺的盈利质量。",
    businessDefinition: "毛利率 = 毛利额 / 销售收入。毛利额通常等于税后收入净额减去主品、赠品和样品成本。",
    technicalDefinition: "优先使用 dm.dm_fina_sales_profit_sum；收入字段看 nnet_inc，成本字段看 nprod_amt、ngift_amt、nsample_amt。",
    formula: "(nnet_inc - nprod_amt - ngift_amt - nsample_amt) / nnet_inc",
    scope: "财务月报、经营复盘、店铺和品类利润分析",
    excludedScope: "不直接用于含平台扣点、推广费分摊的经营毛利口径",
    relatedTables: ["dm.dm_fina_sales_profit_sum", "dm.dw_f_fina_grossprofit_sum"],
    relatedFields: ["nnet_inc", "nprod_amt", "ngift_amt", "nsample_amt"],
    relatedResources: ["毛利率表.cpt", "dm_fina_sales_profit_sum.hpl"],
    evidenceRefs: ["res_fina_profit", "dm.dm_fina_sales_profit_sum"],
    createdBy: "范佳录",
    owner: "财务 BI 组",
    visibility: "company",
    approvals: [
      { role: "BI 工程师", approver: "Jason", status: "approved", approvedAt: "2026-07-28" },
      { role: "财务", approver: "财务负责人", status: "approved", approvedAt: "2026-07-28" },
      { role: "运营", approver: "经营分析", status: "pending" },
    ],
    tags: ["财务指标", "利润分析", "报表口径", "Agent 可用"],
    version: "v1.3",
    updatedAt: "2026-07-28",
    expiresAt: "2026-12-31",
    conflicts: ["经营毛利率"],
    agentVisible: true,
    usageRecords: [
      { agent: "知识探索 Agent", usedAt: "2026-07-28 18:21", context: "回答“毛利率怎么算”时引用" },
      { agent: "BI 分析 Agent", usedAt: "2026-07-28 19:04", context: "生成经营复盘报告前检索" },
    ],
    versionHistory: [
      { version: "v1.3", author: "范佳录", changedAt: "2026-07-28", note: "补充赠品与样品成本字段" },
      { version: "v1.2", author: "Jason", changedAt: "2026-07-27", note: "增加财务认证记录" },
    ],
  },
  {
    id: "kn_field_net_income",
    title: "收入净额字段映射",
    type: "field_mapping",
    status: "approved",
    source: "exploration",
    content: "公司财务利润表里的收入净额字段已经存在，不应再用 GMV 退货金额临时拼公式。",
    businessDefinition: "收入净额代表扣除退货、退款等影响后的财务确认收入。",
    technicalDefinition: "dm.dm_fina_sales_profit_sum.nnet_inc 是当前优先字段；旧表停更时必须寻找 Doris 侧新链路。",
    formula: "nnet_inc",
    scope: "利润、毛利率、财务收入类分析",
    excludedScope: "订单明细层即时 GMV 监控",
    relatedTables: ["dm.dm_fina_sales_profit_sum"],
    relatedFields: ["nnet_inc"],
    relatedResources: ["推广总览明细表.cpt", "利润表 ETL"],
    evidenceRefs: ["run_cba3c4e40356", "dm.dm_fina_sales_profit_sum"],
    sourceQuestion: "dm_fina_sales_profit_sum 这个表不是有收入净额吗？",
    sourceExplorationId: "conv_income_net",
    createdBy: "范佳录",
    owner: "财务 BI 组",
    visibility: "company",
    approvals: [
      { role: "BI 工程师", approver: "Jason", status: "approved", approvedAt: "2026-07-28" },
      { role: "财务", approver: "财务负责人", status: "pending" },
    ],
    tags: ["财务指标", "字段映射", "探索沉淀", "Agent 可用"],
    version: "v1.0",
    updatedAt: "2026-07-28",
    conflicts: [],
    agentVisible: true,
    usageRecords: [{ agent: "知识探索 Agent", usedAt: "2026-07-28 20:10", context: "追问收入净额时复用" }],
    versionHistory: [{ version: "v1.0", author: "范佳录", changedAt: "2026-07-28", note: "从探索会话保存" }],
  },
  {
    id: "kn_report_inventory",
    title: "分销客户分仓库存取数",
    type: "report_logic",
    status: "pending",
    source: "exploration",
    content: "分销客户分仓统计报表的库存来自底层 DW 库存表，并通过金蝶库存链路补足。",
    businessDefinition: "按仓库与物料汇总可用库存，用于分销客户分仓看板。",
    technicalDefinition: "主链路为 dbo.T_STK_INVENTORY 到 dw.dw_f_kd_scm_inventory，再被 CPT 引用。",
    formula: "NBASEQTY where VSTOCKSTATUSID = '10000'",
    scope: "分销客户分仓数据统计报表",
    excludedScope: "在途库存、冻结库存、非正常库存状态",
    relatedTables: ["dw.dw_f_kd_scm_inventory", "dbo.T_STK_INVENTORY"],
    relatedFields: ["NBASEQTY", "VSTOCKSTATUSID", "WH-GZ03-1"],
    relatedResources: ["分销客户分仓数据统计报表.cpt", "dw_f_kd_scm_inventory.hpl"],
    evidenceRefs: ["res_16f7a758d1489e75", "res_61f77fed36ffa740"],
    sourceQuestion: "库存是怎么取数的？",
    sourceExplorationId: "conv_inventory",
    createdBy: "范佳录",
    owner: "供应链 BI 组",
    visibility: "team",
    approvals: [
      { role: "BI 工程师", approver: "Jason", status: "approved", approvedAt: "2026-07-28" },
      { role: "运营", approver: "仓储运营", status: "pending" },
    ],
    tags: ["库存分析", "报表口径", "数据链路"],
    version: "v0.9",
    updatedAt: "2026-07-28",
    conflicts: [],
    agentVisible: true,
    usageRecords: [],
    versionHistory: [{ version: "v0.9", author: "范佳录", changedAt: "2026-07-28", note: "等待业务确认仓库范围" }],
  },
  {
    id: "kn_dimension_channel",
    title: "渠道维度",
    type: "dimension_definition",
    status: "approved",
    source: "manual",
    content: "渠道用于统一销售额、GMV、推广费用等经营分析的拆分维度。",
    businessDefinition: "按平台、店铺和销售渠道归属统一观察业务表现。",
    technicalDefinition: "优先使用平台编码和店铺维表，不直接使用报表展示名做 join。",
    formula: "",
    scope: "销售、投放、利润、复购分析",
    excludedScope: "线下特殊活动的临时渠道编码",
    relatedTables: ["dim.dim_store", "dim.dim_platform"],
    relatedFields: ["platform_id", "store_id", "channel_type"],
    relatedResources: ["渠道映射字典.xlsx"],
    evidenceRefs: ["dim.dim_store"],
    createdBy: "BI 工程组",
    owner: "数据平台组",
    visibility: "company",
    approvals: [{ role: "BI 工程师", approver: "Jason", status: "approved", approvedAt: "2026-07-20" }],
    tags: ["销售分析", "运营指标", "Agent 可用"],
    version: "v2.1",
    updatedAt: "2026-07-20",
    conflicts: [],
    agentVisible: true,
    usageRecords: [],
    versionHistory: [{ version: "v2.1", author: "BI 工程组", changedAt: "2026-07-20", note: "补充抖音渠道归属" }],
  },
  {
    id: "kn_formula_promo_fee",
    title: "推广费用口径",
    type: "formula_definition",
    status: "conflicted",
    source: "exploration",
    content: "推广费用存在财务、抖音人工和商品分摊三套并行口径，需要按使用场景选择。",
    businessDefinition: "推广花费可以按财务系统、平台人工填报或商品分摊观察。",
    technicalDefinition: "dm_fina_vpromotion_channel_type、fill_dy_gmv_expenses_sum、dw_f_cmmg_promoexpen_split_list 均可命中。",
    formula: "按口径选择 nexpenditure / 平台推广费 / nexpen",
    scope: "投放复盘、渠道费用、品类分摊",
    excludedScope: "未确认分摊口径前不写入统一经营指标",
    relatedTables: ["dm.dm_fina_vpromotion_channel_type", "dm.fill_dy_gmv_expenses_sum", "dw.dw_f_cmmg_promoexpen_split_list"],
    relatedFields: ["nexpenditure", "nexpen"],
    relatedResources: ["推广总览明细表.cpt"],
    evidenceRefs: ["run_a822b28a2c9a"],
    sourceQuestion: "推广费用",
    sourceExplorationId: "conv_promo",
    createdBy: "范佳录",
    owner: "投放分析组",
    visibility: "team",
    approvals: [
      { role: "BI 工程师", approver: "Jason", status: "approved", approvedAt: "2026-07-28" },
      { role: "财务", approver: "财务负责人", status: "pending" },
      { role: "运营", approver: "投放运营", status: "pending" },
    ],
    tags: ["运营指标", "渠道分析", "有冲突", "报表口径"],
    version: "v0.8",
    updatedAt: "2026-07-28",
    conflicts: ["推广花费", "投放费用"],
    agentVisible: false,
    usageRecords: [{ agent: "知识探索 Agent", usedAt: "2026-07-28 21:05", context: "提示用户选择三套口径" }],
    versionHistory: [{ version: "v0.8", author: "范佳录", changedAt: "2026-07-28", note: "标记为冲突态，等待财务和运营确认" }],
  },
];
